### PR TITLE
week4 & week5 home work submit 

### PR DESCRIPTION
**Pull request by joesound**
hi 澎澎 I'm Wei-Long 
my week4 & week5 home work route as below, pls help check it, thank you
week4:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/2 (/attraction/<id>)

week5:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/12 (/attraction/<id>)
http://52.73.173.92:3000/booking

### CODE REVIEW

**Comment by cwpeng** [comment]
your server cannot response for now.

**Comment by joesound** [comment]
hi 澎澎 I'm Wei-Long
I re-start my server, pls try again, thank you
my week4 & week5 home work route as below, pls help check it, thank you
week4:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/2 (/attraction/)

week5:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/12 (/attraction/)
http://52.73.173.92:3000/booking

**Comment by cwpeng** [comment]
1. Use input tag with type password for password input.
2. Set cursor style to pointer in any clickable elements.

**Comment by joesound** [comment]
hi 澎澎,revise the issue as below 
1. Use input tag with type password for password input. => done, change password input tag from text to password.
2. Set cursor style to pointer in any clickable elements. => done, add style in clickable elements.
pls help check it, thank you

week4:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/2 (/attraction/)

week5:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/12 (/attraction/)
http://52.73.173.92:3000/booking

**Comment by cwpeng** [comment]
In some mobile devices, your layout is not acceptable. Example shown below:

未命名-3

**Comment by joesound** [comment]
hi 澎澎,I fixed the attraction page broken in some devices issue.
pls help check it, thank you
week4:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/2 (/attraction/)

week5:
http://52.73.173.92:3000/ (index)
http://52.73.173.92:3000/attraction/12 (/attraction/)
http://52.73.173.92:3000/booking

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
