### PR TITLE
本週作業上傳

### PR DESCRIPTION
**Pull request by joesound**
陳韋龍
http://52.73.173.92:3000/api/attractions?page=1
http://52.73.173.92:3000/api/attractions?page=0&keyword=溫泉
http://52.73.173.92:3000/api/attraction/10

### CODE REVIEW

**Comment by cwpeng** [comment]
I need your online URLs for testing.

**Comment by joesound** [comment]
姓名:陳韋龍
測試網址:
http://52.73.173.92:3000/api/attractions?page=1
http://52.73.173.92:3000/api/attractions?page=0&keyword=溫泉
http://52.73.173.92:3000/api/attraction/10

**Comment by cwpeng** [comment]
"images" field of response should be an array contains all image URLs separately, not a comma joined string.

fix issue and leave comment for me to review again.

**Comment by joesound** [comment]
I have fixed the issue 
Use the method of python string format

**Review by cwpeng — COMMENTED** [review]
We never get all possible matching data at once. Use LIMIT statement in your SQL query to do range selection. I mean you should use LIMIT in SQLs below and change related code necessory.
```
SELECT main.id,main.name,CAT2.cat2_name,main.description,main.address,bus.bus_name,mrt.mrt_name,main.longitude,main.latitude,image_sort.image_url FROM ((((main INNER JOIN CAT2 ON main.CAT2_id = CAT2.id) INNER JOIN bus ON main.id = bus.main_id) INNER JOIN mrt ON main.mrt_id = mrt.id) INNER JOIN (SELECT image.main_id, group_concat(image.image_url order by image.main_id SEPARATOR ',') image_url FROM image GROUP BY image.main_id) image_sort ON main.id = image_sort.main_id) WHERE main.description LIKE %s;

SELECT main.id,main.name,CAT2.cat2_name,main.description,main.address,bus.bus_name,mrt.mrt_name,main.longitude,main.latitude,image_sort.image_url FROM ((((main INNER JOIN CAT2 ON main.CAT2_id = CAT2.id) INNER JOIN bus ON main.id = bus.main_id) INNER JOIN mrt ON main.mrt_id = mrt.id) INNER JOIN (SELECT image.main_id, group_concat(image.image_url order by image.main_id SEPARATOR ',') image_url FROM image GROUP BY image.main_id) image_sort ON main.id = image_sort.main_id);
```

Fix issue and leave comment for me to review again.

**Comment by joesound** [comment]
Sorry, that was my fault,
I am using getattactions.py as my main query script which adopt the Limit statement for query database.

**Comment by cwpeng** [comment]
OK. Got it. But I need you request me review again from right side in this page. There is a clickable icon you can re-request review.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
