### PR TITLE
第二週作業上傳

### PR DESCRIPTION
**Pull request by joesound**
陳韋龍
連入網址
http://52.73.173.92:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
1. Background of key visual section should be a gradient color.
2. Aspect ratio (長寬比例) of background image of key visual section is broken in the mobile version.
3. Search icon does not align with design obviousely.
4. Text color of key visual section should be white.
5. Only navigator bar will fixed on top when we scroll down the page.

Fix issues and leave comment for me to review again.

**Comment by joesound** [comment]
hi澎澎, i am wei-long
week2 submit : http://52.73.173.92:3000/
I have revise below issues
1.Background of key visual section should be a gradient color. => add a gradient color same as the bible.
2.Aspect ratio (長寬比例) of background image of key visual section is broken in the mobile version. => optimize the image size.
3.Search icon does not align with design obviousely. => choose the icon which align design.
4.Text color of key visual section should be white. => change the color of the text to white.
5.Only navigator bar will fixed on top when we scroll down the page. =>  adjust fixed element on DOM.

**Comment by cwpeng** [comment]
Better, but still issues below:
1. We should align attraction list center in any screen size.
2. We should load up to max pages of data. Your code will load repeatedly after last page.



未命名-2

**Comment by joesound** [comment]
hi 澎澎, I am Wei-Long  
Week2 home work: http://52.73.173.92:3000/
1.We should align attraction list center in any screen size. => I revise the style sheet to make attraction list align center in all screen size.
2.We should load up to max pages of data. Your code will load repeatedly after last page. => I fixed the repeatedly query data problem, also load up to max pages of data by use wrap which is flex character.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
